// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDIcr6Luc-dkdFXo5H9e9bkSmIr0BGZFQ',
    appId: '1:422032897396:web:31150282c6205561b5e821',
    messagingSenderId: '422032897396',
    projectId: 'quizapp-ac5ec',
    authDomain: 'quizapp-ac5ec.firebaseapp.com',
    storageBucket: 'quizapp-ac5ec.appspot.com',
    measurementId: 'G-VZFQ6FQ15Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNNRB0uOSyfM0tgyqJUJCuytSb7HJQyss',
    appId: '1:422032897396:android:dc333c4e70416470b5e821',
    messagingSenderId: '422032897396',
    projectId: 'quizapp-ac5ec',
    storageBucket: 'quizapp-ac5ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJA_0C5FRCTD65ZPyoj8W2rObpF-kQP_A',
    appId: '1:422032897396:ios:6bb4b7b7f857a796b5e821',
    messagingSenderId: '422032897396',
    projectId: 'quizapp-ac5ec',
    storageBucket: 'quizapp-ac5ec.appspot.com',
    iosClientId: '422032897396-eqhl692o2rgladpofe3bbi1bnqgmi1o0.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJA_0C5FRCTD65ZPyoj8W2rObpF-kQP_A',
    appId: '1:422032897396:ios:6bb4b7b7f857a796b5e821',
    messagingSenderId: '422032897396',
    projectId: 'quizapp-ac5ec',
    storageBucket: 'quizapp-ac5ec.appspot.com',
    iosClientId: '422032897396-eqhl692o2rgladpofe3bbi1bnqgmi1o0.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
